spring:
  application:
    name: notification-service
  rabbitmq:
    template:
      default-receive-queue: prescription-queue
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        missing-queues-fatal: false
server:
  port: 8084